# Generated by Django 5.1.7 on 2025-03-23 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('explanation', models.TextField()),
                ('options', models.JSONField()),
            ],
        ),
    ]
